import { ProposalData } from '@/types/proposal';

const today = new Date().toISOString().split('T')[0];

export const defaultProposalData: ProposalData = {
  proposalNumber: 'PROP-2026-001',
  title: 'Desenvolvimento de Website Institucional e Identidade Visual',
  projectSummary: 'Apresentação comercial e técnica para modernização da presença digital da empresa, visando aumento na conversão de leads, autoridade de marca e performance mobile.',
  issueDate: today,
  currency: 'BRL',
  theme: 'corporate',
  discount: 10,
  discountType: 'percentage',
  provider: {
    name: 'Studio Nexus Design & Tech',
    document: '12.345.678/0001-90',
    email: 'contato@studionexus.com.br',
    phone: '(11) 98765-4321',
    address: 'Av. Paulista, 1000, Sala 52 - São Paulo, SP',
    website: 'https://studionexus.com.br',
    primaryColor: '#1e3a8a',
    pixKey: '12.345.678/0001-90',
    pixType: 'cnpj',
    bankInfo: 'Banco Inter (077) • Ag: 0001 • CC: 9876543-2 • Favorecido: Studio Nexus Ltda',
  },
  client: {
    name: 'Mariana Silveira',
    companyName: 'InovaTech Consultoria Ltda',
    contactRole: 'Diretora de Operações',
    document: '98.765.432/0001-10',
    email: 'mariana@inovatech.com.br',
    phone: '(11) 91234-5678',
    address: 'Rua Funchal, 418 - Vila Olímpia, São Paulo - SP',
  },
  items: [
    {
      id: '1',
      description: 'Redesign de Identidade Visual e Manual de Marca',
      details: 'Criação de logotipo principal e variações, paleta de cores institucional, tipografia, grafismos e guia de aplicação em PDF de 20 páginas.',
      quantity: 1,
      unitPrice: 2800,
    },
    {
      id: '2',
      description: 'Desenvolvimento de Website Responsivo em Next.js',
      details: 'Estruturação de 5 páginas institucionais (Home, Sobre, Serviços, Portfólio, Contato), código otimizado para SEO, Core Web Vitals e integração com WhatsApp.',
      quantity: 1,
      unitPrice: 4500,
    },
    {
      id: '3',
      description: 'Configuração de Infraestrutura, Domínio e SSL',
      details: 'Deploy profissional em nuvem, configuração de DNS no Cloudflare e certificado de segurança SSL.',
      quantity: 1,
      unitPrice: 600,
    },
    {
      id: '4',
      description: 'Treinamento de Gestão e Suporte Inicial',
      details: 'Gravação de vídeo tutorial guiado para gerenciamento da página + 30 dias de suporte e ajustes pós-lançamento.',
      quantity: 1,
      unitPrice: 800,
    },
  ],
  milestones: [
    {
      id: '1',
      title: 'Alinhamento e Moodboard',
      deadline: '5 dias úteis',
      deliverable: 'Apresentação de paleta, tipografia e direcionamento visual',
    },
    {
      id: '2',
      title: 'Layout & Protótipo do Site',
      deadline: '10 dias úteis',
      deliverable: 'Apresentação das telas completas para aprovação',
    },
    {
      id: '3',
      title: 'Programação & Homologação',
      deadline: '15 dias úteis',
      deliverable: 'Ambiente de teste funcional para revisão final',
    },
    {
      id: '4',
      title: 'Publicação Oficial & Entrega',
      deadline: '20 dias úteis',
      deliverable: 'Site no ar no domínio oficial e entrega dos arquivos-fonte',
    },
  ],
  conditions: {
    deliveryTime: '20 dias úteis a contar após o recebimento dos materiais e briefing aprovado',
    paymentMethod: '50% de entrada no aceite e 50% na homologação e entrega final (via PIX ou Transferência)',
    validityDays: 15,
    warranty: 'Garantia de 30 dias corridos para correção de eventuais bugs ou ajustes técnicos sem custo adicional.',
    extraScopeTerms: 'Alterações ou novas funcionalidades fora do escopo descrito nesta proposta serão orçadas à taxa de R$ 120,00/hora.',
    notes: '• Os textos, fotografias institucionais e acessos necessários para o início dos trabalhos serão fornecidos pelo contratante.\n• O cancelamento após início do desenvolvimento prevê retenção do valor de entrada referente às horas trabalhadas.\n• A assinatura desta proposta ou confirmação via e-mail/WhatsApp formaliza o início da execução.',
  },
};

export const emptyProposalData: ProposalData = {
  proposalNumber: `PROP-${new Date().getFullYear()}-001`,
  title: '',
  projectSummary: '',
  issueDate: today,
  currency: 'BRL',
  theme: 'corporate',
  discount: 0,
  discountType: 'percentage',
  provider: {
    name: '',
    document: '',
    email: '',
    phone: '',
    address: '',
    website: '',
    primaryColor: '#1e3a8a',
    pixKey: '',
    pixType: 'manual',
    bankInfo: '',
  },
  client: {
    name: '',
    companyName: '',
    contactRole: '',
    document: '',
    email: '',
    phone: '',
    address: '',
  },
  items: [
    {
      id: '1',
      description: '',
      details: '',
      quantity: 1,
      unitPrice: 0,
    },
  ],
  milestones: [],
  conditions: {
    deliveryTime: '15 dias úteis',
    paymentMethod: '50% de entrada + 50% na entrega',
    validityDays: 10,
    warranty: 'Garantia de 30 dias para correções e suporte.',
    extraScopeTerms: 'Itens adicionais serão orçados separadamente.',
    notes: '',
  },
};
